// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var verifier = artifacts.require('Verifier');

contract('Verifier', accounts => {
    
    const user  = accounts[0];
    const rproof = require("./proof_right");

    describe('Testing square code verifier', ()=>{
        beforeEach(async () => {
            this.contract = await verifier.new({from: user})
        })
    })

    it('Verificating with the right proof', async () => {
        let proof_result = await this.contract.verifyTx.call(
            rproof.a,
            rproof.b,
            rproof.c,
            rproof.inputs,
            {from: user}
        );
    assert.equal(true, proof_result, "Verifier not working");
    })
})

// Test verification with correct proof
// - use the contents from proof.json generated from zokrates steps


// Test verification with incorrect proof

